local Remap = require("jedwalton.keymap")
local nnoremap = Remap.nnoremap

nnoremap("<C-p>", ":Telescope")
nnoremap("<leader>ps", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})
end)
nnoremap("<C-p>", function()
    require('telescope.builtin').git_files()
end)
nnoremap("<Leader>pf", function()
    require('telescope.builtin').find_files()
end)
nnoremap("<leader>pw", function()
    require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
nnoremap("<leader>pb", function()
    require('telescope.builtin').buffers()
end)
nnoremap("<leader>vh", function()
    require('telescope.builtin').help_tags()
end)
nnoremap("<leader>vrc", function()
    require('jedwalton.telescope').search_dotfiles({ hidden = true })
end)
nnoremap("<leader>va", function()
    require('jedwalton.telescope').anime_selector()
end)
nnoremap("<leader>vc", function()
    require('jedwalton.telescope').chat_selector()
end)
nnoremap("<leader>gc", function()
    require('jedwalton.telescope').git_branches()
end)
nnoremap("<leader>td", function()
    require('jedwalton.telescope').dev()
end)



